### PR TITLE
Static DNS HLD

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
The access to the DNS in SONiC is organized via the resolver configuration file (/etc/resolv.conf). resolv.conf is the plain text file that contains the human-readable configuration. It is used across various subsystems in the SONiC to translate domain names into IP addresses. 

With the current implementation dynamic DNS configuration can be received from the DHCP server or static configuration can be set manually by the user. However, SONiC doesn't provide any protection for the static configuration. The configuration that is set by the user can be overwritten with the dynamic configuration at any time.

The proposed solution is to add support for static DNS configuration into Config DB. To be able to choose between dynamic and static DNS configurations `resolvconf` package.

<html>
<body>

PR title | State | Status | Dependencies | Unitest | Owner | Included in 202211
-- | -- | -- | -- | -- | -- | --
[[DNS] yang model for static DNS](https://github.com/sonic-net/sonic-buildimage/pull/13834) | GitHub issue/pull request detail| checkers passed  | N/A | added | @oleksandrivantsiv  | no
[[dns] Add support for static DNS configuration.](https://github.com/sonic-net/sonic-buildimage/pull/14239) | GitHub issue/pull request detail| checkers passed  | N/A | added | @oleksandrivantsiv  | no
[[dns] Implement config and show commands for static DNS.](https://github.com/sonic-net/sonic-utilities/pull/2737) | GitHub issue/pull request detail| checkers passed  | https://github.com/sonic-net/sonic-buildimage/pull/14239 | added | @oleksandrivantsiv  | no
[[hostcfgd][dns] Subscribe to DNS_NAMESERVER table to react to static DNS configuration changes.](https://github.com/sonic-net/sonic-host-services/pull/49) | GitHub issue/pull request detail| checkers passed  | https://github.com/sonic-net/sonic-buildimage/pull/14239 | added | @oleksandrivantsiv  | no

</body>
</html>

### CODE REVIEW

**Comment by ganglyu** [comment]
Hi @oleksandrivantsiv
This solution can be used to fix our production issue. We found some Mellanox device with wrong DNS configuration:
user@sonic:~$ cat /etc/resolv.conf
domain ztgroup.com
search ztgroup.com
nameserver 10.1.90.130
nameserver 10.1.90.101

It seems that TOR assembly vendor is using internal image 20191130.84, and they modified DNS configuration. And in our production environment, our upgrade system finds that 20191130.84 is the latest image, so there's no need to upgrade. And then we got the wrong DNS configuration in our production environment.

**Comment by ganglyu** [comment]
@oleksandrivantsiv 
Can we use minigraph.py to generate static DNS configuration for internal image?
Because TOR assembly vendor is using internal image, if we use minigraph.py to generate static DNS configuration, how can they modify DNS configuration? Maybe they can use CLI to remove static DNS configuration?

**Comment by oleksandrivantsiv** [comment]
> @oleksandrivantsiv Can we use minigraph.py to generate static DNS configuration for internal image? Because TOR assembly vendor is using internal image, if we use minigraph.py to generate static DNS configuration, how can they modify DNS configuration? Maybe they can use CLI to remove static DNS configuration?

@ganglyu I didn't add support for static DNS configuration into minigraph.py, but it is something we can do.
It is possible to use CLI to manipulate with DNS configuration. We will have add, remove, and show commands

**Comment by oleksandrivantsiv** [comment]
@ganglyu can we update the minigraph.py in the second stage? The available changes are completely independent of the minigrapth and can be pushed independently. We will prioritize this for Apr.

**Comment by oleksandrivantsiv** [comment]
> > @ganglyu can we update the minigraph.py in the second stage? The available changes are completely independent of the minigrapth and can be pushed independently. We will prioritize this for Apr.
> 
> sure

@ganglyu can you please approve this PR if you are ok with the proposed design? I'll open another PR with the minigrapth related changes.

**Review by ganglyu — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Comment by StormLiangMS** [comment]
@oleksandrivantsiv new feature, pls wait for next branch cut.

**Pull request merged**
