### PR TITLE
Updating Contributors

### PR DESCRIPTION
**Pull request by ixodie**
I was trying to add a new community contributor and noticed that the website uses a single image which has not been updated in years.  The source of the image cannot be found.

I implemented a dynamic responsive display of the contibutors.json file using js and added all of the images to a new directory and put that data into the json.

I could not find 3 companies (I cannot read Chinese), but I left the original images in case someone can determine who they are.  They are noted in the json file as "unknown".

Several companies have been acquired, I did not include any acquired companies provided that the new company is already listed (ex. Apstra/Juniper).

### CODE REVIEW

**Comment by ixodie** [comment]
@zhangyanzhao @kannankvs Can someone please review this?  I submitted it 2 months ago.  Pretty straightforward changes.

**Comment by zhangyanzhao** [comment]
@ixodie  will the "unknown" logo be displayed on your new list? I can not see the preview of your new page, hard to know which one has been removed, which one is kept.

**Comment by ixodie** [comment]
> @ixodie will the "unknown" logo be displayed on your new list? I can not see the preview of your new page, hard to know which one has been removed, which one is kept.

The logos are still there, I just didn't know the name or the URL.

**Review by zhangyanzhao — APPROVED** [review]

**Comment by ixodie** [comment]
@zhangyanzhao I suggest you look into why the Github page is not serving the json file.  Right now the contributors does not load properly on the wiki.

**Comment by ixodie** [comment]
Screenshot 2023-02-14 at 4 55 21 PM

**Comment by kannankvs** [comment]
@ixodie  We would like to discuss this issue with you. Request you to kindly share your email id for further discussion.

**Comment by zhangyanzhao** [comment]
I will revert this PR.

**Comment by zhangyanzhao** [comment]
@ixodie  I like your idea to manage the logos with dynamic responsive display. Can you please work with Kannan to check the failure and raise another PR? Thanks.

**Pull request merged**
