### PR TITLE
Changes to handling of single path and multi path NextHOP Group msg

### PR DESCRIPTION
**Pull request by nkelapur**
Changes to handling of single path and multi path NextHOP Group msg

### CODE REVIEW

**Comment by ntt-omw** [comment]
@nkelapur The Fpmsyncd HLD has been moved to another directory. Thanks.
https://github.com/sonic-net/SONiC/blob/master/doc/pic/hld_fpmsyncd.md

**Comment by nakano-omw** [comment]
@nkelapur The Fpmsyncd HLD has been moved to another directory. Thanks.
https://github.com/sonic-net/SONiC/blob/master/doc/pic/hld_fpmsyncd.md

**Comment by nakano-omw** [comment]
@nkelapur Is this PR related to the following issue?
https://github.com/sonic-net/SONiC/issues/1594

**Comment by nkelapur** [comment]
> @nkelapur Is this PR related to the following issue? #1594

Yes, its related to the additional changes on top of https://github.com/sonic-net/SONiC/pull/1596 .. 
Looks like I took from incorrect/older version and branch. Also I need to add more details. Will add more changes and update as per the latest hld and commit here

**Comment by nkelapur** [comment]
These changes are pushed by another updated PR https://github.com/sonic-net/SONiC/pull/1636
Please review them there.

**Comment by nkelapur** [comment]
Changes are pushed with update PR https://github.com/sonic-net/SONiC/pull/1636 hence closing this PR

**Pull request closed without merging**
