### PR TITLE
[PR tracker] SONiC ECMP calculator

### PR DESCRIPTION
**Pull request by liorghub**
The purpose of ECMP calculator is to calculate which IP interface ECMP will choose and return the physical interface packet will egress from. Packet is defined by a JSON file given as an argument to the tool.
An equal cost multipath (ECMP) is formed when routing table contains multiple next hop addresses for the same destination IP address. ECMP will load balance the outbound traffic between the IP interfaces. 

| PR title                                                                                             | State                                                                                                               | Status                                                                                                                  | Dependencies                                                                                                             | Unitest                                                                                                              | Owner                                                                                                              | Included in  202211                                                                                                              |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------| ------------------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------| -------------------------------------------------------------------------------------------------------------------| -------------------------------------------------------------------------------------------------------------------|
| [Add ECMP calculator tool](https://github.com/sonic-net/sonic-buildimage/pull/12482) | GitHub issue/pull request detail   | checkers passed  | https://github.com/sonic-net/sonic-buildimage/pull/12840  | tests implemented in sonic-mgmt  | @liorghub | Yes |
| [[Mellanox] Add SDK hash calculator debian and update SDK makefile to compile it](https://github.com/sonic-net/sonic-buildimage/pull/12840) | GitHub issue/pull request detail   | checkers passed  | none  |  N/A | @liorghub | Yes |
| [Add CLI command for ECMP calculator](https://github.com/sonic-net/sonic-utilities/pull/2538) | GitHub issue/pull request detail   | checkers passed  | none  |  unittest added | @liorghub | Yes |
| [[Mellanox] Update ECMP calculator README](https://github.com/sonic-net/sonic-buildimage/pull/13051) | GitHub issue/pull request detail   | checkers passed  | none  |  N/A | @liorghub | Yes |
| [[Mellanox] [ECMP calculator] Add script usage and more information to script description in help option](https://github.com/sonic-net/sonic-buildimage/pull/13493) | GitHub issue/pull request detail   | checkers passed | none  |  N/A | @liorghub | Yes |
| [[Mellanox] [ECMP calculator] Add support for 4600/4600C/2201 platforms with different interface naming method](https://github.com/sonic-net/sonic-buildimage/pull/13814) | GitHub issue/pull request detail   | checkers passed | none  |  N/A | @liorghub | Yes |

### CODE REVIEW

**Comment by liat-grozovik** [comment]
all required PRs were merged.
@liorghub  please confirm all is in 202211 and if so, we can add it to the RN.

**Comment by liorghub** [comment]
@liat-grozovik 
I have submitted one more PR (https://github.com/sonic-net/sonic-buildimage/pull/13493) to enhance the help option. 
Once it is in, I will confirm.

**Comment by liorghub** [comment]
> all required PRs were merged. @liorghub please confirm all is in 202211 and if so, we can add it to the RN.

@liat-grozovik All required PRs are included in master and 202211.

**Comment by liat-grozovik** [comment]
@zhangyanzhao now that the code PRs are merged and all available in 202211 should we close the tracking PR?

**Comment by liat-grozovik** [comment]
> @zhangyanzhao now that the code PRs are merged and all available in 202211 should we close the tracking PR?

@zhangyanzhao what should be done with the tracking PR now that all the PRs were merged?

**Comment by shishao7sxm** [comment]
@liorghub Hi, This is an interesting functionality, i can imagine the operation team will love that. From your perspective, any other scenarios can leverage this capability? SDN?

**Comment by zhangyanzhao** [comment]
I am fine to close. Thanks.

**Comment by zhangyanzhao** [comment]
It is better to merge it to keep a record.  @kannankvs for your awareness, can we add this into the 202211 release notes? Thanks.

**Review by zhangyanzhao — APPROVED** [review]

**Pull request merged**
