### PR TITLE
HLD update: Adding support for FPGA devices in PDDF

### PR DESCRIPTION
**Pull request by FuzailBrcm**
HW vendors use FPGA devices in their platform design. 

In one of the use cases, the FPGA is connected to CPU via I2C bus. Such FPGAs are similar to any other I2C device with I2C address and adapter where they are connected. We are calling it FPGAI2C.

The other use case is where the FPGA is connected to CPU via PCIe. The FPGA also acts as the I2C controller and other devices are controlled by it. We are calling this design as FPGAPCIe. 

This update in the PDDF HLD deals with the support for these two kind of FPGAs. 

|**Repo**  |    **PR title**    |  **State** |
|-----------|----------------|----------
| sonic-buildimage |  [Adding support for I2CFPGA in PDDF](https://github.com/sonic-net/sonic-buildimage/pull/13475) |  |
| sonic-buildimage |  [Adding support for FPGAPCIe in PDDF](https://github.com/sonic-net/sonic-buildimage/pull/13476)  |   |
| sonic-buildimage | [Enabling FPGA device support in PDDF](https://github.com/sonic-net/sonic-buildimage/pull/13477) |   |
| sonic-buildimage | [Modifying the PDDF common platform APIs as per the LED driver changes](https://github.com/sonic-net/sonic-buildimage/pull/13474) |   |

### CODE REVIEW

**Comment by FuzailBrcm** [comment]
@celestica-gl , @qnos 

Please review.

**Comment by FuzailBrcm** [comment]
@jostar-yang please help review

**Review by qnos — APPROVED** [review]

**Review by jostar-yang — DISMISSED** [review]
It is fine to me.

**Review by jostar-yang — APPROVED** [review]
The changes is fine to me.

**Comment by zhangyanzhao** [comment]
[#13484 ](https://github.com/sonic-net/sonic-buildimage/pull/13848) need be added into the PR list @FuzailBrcm  can you please help to update this HLD? Thanks.

**Comment by zhangyanzhao** [comment]
@lguohan  can you please check and merge this PR? Thanks.

**Review by yxieca — APPROVED** [review]

**Pull request merged**
