### PR TITLE
SYSTEM READY

### PR DESCRIPTION
**Pull request by sg893052**
Support for System Ready ( Followup to https://github.com/Azure/SONiC/pull/875)

<html>
<body>

Repo | PR title | State
-- | -- | --
sonic-buildimage | <a href="https://github.com/Azure/sonic-buildimage/pull/10479" data-hovercard-type="pull_request" data-hovercard-url="/Azure/sonic-buildimage/pull/10479/hovercard">System Ready</a>  | 
sonic-utilities | <a href="https://github.com/Azure/sonic-utilities/pull/1851" data-hovercard-type="pull_request" data-hovercard-url="/Azure/sonic-utilities/pull/1851/hovercard">Show commands for System Ready</a> | 

</body>
</html>

### CODE REVIEW

**Comment by sg893052** [comment]
Followup to https://github.com/Azure/SONiC/pull/875

**Comment by adyeung** [comment]
@Junchao-Mellanox pls help review and signoff

**Review by Junchao-Mellanox — APPROVED** [review]

**Review by sujinmkang — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@sg893052 will you consider having a sonic-mgmt test for it? if not, can you please clarfiy how we can ensure this feature is fully working on every release? do we have any functional test running on vsimage?

**Comment by liat-grozovik** [comment]
@sg893052 i am missing the command reference update with the new CLIs. it is not part of the PR listed in this description. Do you have another PR which you can add to the list? if not, can you please have a dedicated one and add it to the list of PRs to be tracked?
BTW the provided the tests in the utilities are very minimal and i am not sure they are covering all the flows. Could you please consider enhancing it?

@sujinmkang  FYI

**Pull request merged**
