### PR TITLE
Update supported_devices_platforms_md.sh

### PR DESCRIPTION
**Pull request by Yuval-Mellanox**
Added support for SN5600

### CODE REVIEW

**Comment by kannankvs** [comment]
Reviewed and approved. We will raise a separate PR for updating the html file.

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@Yuval-Mellanox  please resolve conflicts and i will merge

**Comment by liat-grozovik** [comment]
@kannankvs i would like to suggest removing the numbers from the list as each time one would like to add a supported device per vendor he needs to changes all the sequential numbers .
another option it to have per vendor section and numbers per vendor.
what do you think?

**Comment by liat-grozovik** [comment]
has integrated to another PR and will be available on the next generated md file.
no need for this pr

**Pull request closed without merging**
