### PR TITLE
[TWAMP] Add TWAMP Light feature HLD

### PR DESCRIPTION
**Pull request by huseratgithub**
This document provides general information about the TWAMP Light feature implementation in SONiC.
This feature has been tracked in https://github.com/sonic-net/SONiC/issues/1192

Repo | PR title | State
-- | -- | --
sonic-swss | [TWAMP Light orchagent implementation](https://github.com/sonic-net/sonic-swss/pull/2927) | GitHub issue/pull request detail
sonic-swss-common | [Added TWAMP Light table to schema](https://github.com/sonic-net/sonic-swss-common/pull/823) | GitHub issue/pull request detail
sonic-sairedis | [Support TWAMP Light notification in syncd](https://github.com/sonic-net/sonic-sairedis/pull/1306) | GitHub issue/pull request detail
sonic-utilities | [Added CLIs to support TWAMP Light](https://github.com/sonic-net/sonic-utilities/pull/3011) | GitHub issue/pull request detail
SAI | [Added TWAMP Light API](https://github.com/opencomputeproject/SAI/pull/1786) | GitHub issue/pull request detail

### CODE REVIEW

**Review by guxianghong — APPROVED** [review]

**Comment by zhangyanzhao** [comment]
@huseratgithub can you please update the HLD by using community HLD template https://github.com/sonic-net/SONiC/blob/master/doc/hld_template.md, there are mandatory sections to cover. Thanks.

**Comment by huseratgithub** [comment]
https://github.com/sonic-net/SONiC/pull/1320#issuecomment-1581700725
@zhangyanzhao upding and will submit in the weekend

**Comment by huseratgithub** [comment]
>

**Comment by huseratgithub** [comment]
> @huseratgithub can you please update the HLD by using community HLD template https://github.com/sonic-net/SONiC/blob/master/doc/hld_template.md, there are mandatory sections to cover. Thanks.

@zhangyanzhao  I have update the HLD by template, please help to check and review, thanks

**Comment by zhangyanzhao** [comment]
community review recording https://zoom.us/rec/share/KMpGzdM5XUr3cfO7jfIWmgtgONfyYKA_FZXK_nIB_jZFWj2GtodlReuVH73W0tNs.K32lR8TWbGckHUFO

**Comment by zhangyanzhao** [comment]
This is reviewed in SONiC community.  Please let me know if you want to be reviewer for this feature, thanks.

**Comment by guxianghong** [comment]
@zhangyanzhao We have invite @clarklee-guizhao to reivew this PR, 
Could you please help to add @clarklee-guizhao into the reviewer list, Thanks very much.

**Comment by huseratgithub** [comment]
@zhangyanzhao @yxieca The comments were handled. can you please help to approve/merge?

**Comment by zhangyanzhao** [comment]
Can you please help to add the code PR into this HLD by referring to #806 ? That is required before merging this HLD PR. Thanks.

**Comment by huseratgithub** [comment]
> Can you please help to add the code PR into this HLD by referring to #806 ? That is required before merging this HLD PR. Thanks.
The code PRs have been added

**Review by clarklee-guizhao — APPROVED** [review]
LGTM

**Comment by huseratgithub** [comment]
@zhangyanzhao  @yxieca  Could you please help to approve/merge? Thanks.

**Comment by huseratgithub** [comment]
@clarklee-guizhao Thanks a lot for your review.

**Comment by prsunny** [comment]
@huseratgithub , where is the sonic-mgmt test for this feature?

**Comment by huseratgithub** [comment]
> @huseratgithub , where is the sonic-mgmt test for this feature?

hi @prsunny , sonic-mgmt is an enhancement, let's have it in later phase.

**Comment by zhangyanzhao** [comment]
@eddieruan-alibaba can you please help to find someone in Alibaba to complete the code PR review? Thanks.

**Comment by goomadao** [comment]
Hi @huseratgithub , great feature for us. But do you have any plan about the software solution of TWAMP Light? There is few ASICs supporting the TWAMP offload ASAIK and we're considering to offload timestamping only to the ASIC.

**Comment by guxianghong** [comment]
> Hi @huseratgithub , great feature for us. But do you have any plan about the software solution of TWAMP Light? There is few ASICs supporting the TWAMP offload ASAIK and we're considering to offload timestamping only to the ASIC.

Yes, after completing the phase1 hardware-based TWAMP light, we will immediately start the phase2 software-based TWAMP light which has already been condidered in the TWAMP light HLD.

**Comment by zhangyanzhao** [comment]
one code PR is still open, move to backlog

**Pull request merged**
