### PR TITLE
Vrf lite

### PR DESCRIPTION
**Pull request by haris-khan1596**
High-level design of Virtual Routing and Forwarding-Lite feature in SONiC.

Please see code PR below:
| Repo  | PR title | State |
| ----------------- | ----------------- | ----------------- |
| sonic-utilities | [Add Vrf-Lite CLI Commands](https://github.com/sonic-net/sonic-utilities/pull/2366) | GitHub issue/pull request detail |

### CODE REVIEW

**Comment by Hedgehog-Guru** [comment]
@haris-khan1596 ,
What is the difference between this feature and the very similar which is already exists [sonic-vrf-hld.md](https://github.com/sonic-net/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md)?

From the functional point of view, everything looks the same, except:
- No special “mgmt” VRF is defined.
- No restrictions on VRF name starting with string “Vrf_”.
- CLI is slightly different
  - Was: config vrf add <name>
  - New: config vrflite add <name>

What is the motivation to duplicate the feature? Maybe it is better to improve the current implementation?

**Comment by venkatmahalingam** [comment]
> @haris-khan1596 , What is the difference between this feature and the very similar which is already exists [sonic-vrf-hld.md](https://github.com/sonic-net/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md)?
> 
> From the functional point of view, everything looks the same, except:
> 
> * No special “mgmt” VRF is defined.
> * No restrictions on VRF name starting with string “Vrf_”.
> * CLI is slightly different
>   
>   * Was: config vrf add
>   * New: config vrflite add
> 
> What is the motivation to duplicate the feature? Maybe it is better to improve the current implementation?

I agree, I don't see any convincing details to introduce new prefix 'Vrflite' in the key, why cant we introduce the field in the existing VRF table to accept L3 interface to VRF binding only if the interface is not MPLS enabled.

**Comment by haris-khan1596** [comment]
Yes,  this HLD is similar to [sonic-vrf-hld.md](https://github.com/sonic-net/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md) on the basis of functionality. With this new Vrf-life HLD, we intend to improve the user experience. The motivation is that user will have a clear distinction between the `Vrf` and `Vrf-lite`. We have implemented a new set of commands for [vrf-lite](https://github.com/sonic-net/sonic-utilities/pull/2366) to distinguish between `Vrf-lite` and `Vrf`. See edited comment above to see state of the code PR.
In addition to a new set of commands we have also made a slight modification (addition of an arrow from Config_db to the VRF-CLI) in the current high level [system diagram](https://github.com/sonic-net/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md#sonic-system-diagram-for-vrf) for vrf.

**Comment by venkatmahalingam** [comment]
> Yes, this HLD is similar to [sonic-vrf-hld.md](https://github.com/sonic-net/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md) on the basis of functionality. With this new Vrf-life HLD, we intend to improve the user experience. The motivation is that user will have a clear distinction between the `Vrf` and `Vrf-lite`. We have implemented a new set of commands for [vrf-lite](https://github.com/sonic-net/sonic-utilities/pull/2366) to distinguish between `Vrf-lite` and `Vrf`. See edited comment above to see state of the code PR. In addition to a new set of commands we have also made a slight modification (addition of an arrow from Config_db to the VRF-CLI) in the current high level [system diagram](https://github.com/sonic-net/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md#sonic-system-diagram-for-vrf) for vrf.

I don't see any convincing reason for this HLD yet, please answer my above questions.

**Comment by eddyk-nvidia** [comment]
> > Yes, this HLD is similar to [sonic-vrf-hld.md](https://github.com/sonic-net/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md) on the basis of functionality. With this new Vrf-life HLD, we intend to improve the user experience. The motivation is that user will have a clear distinction between the `Vrf` and `Vrf-lite`. We have implemented a new set of commands for [vrf-lite](https://github.com/sonic-net/sonic-utilities/pull/2366) to distinguish between `Vrf-lite` and `Vrf`. See edited comment above to see state of the code PR. In addition to a new set of commands we have also made a slight modification (addition of an arrow from Config_db to the VRF-CLI) in the current high level [system diagram](https://github.com/sonic-net/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md#sonic-system-diagram-for-vrf) for vrf.
> 
> I don't see any convincing reason for this HLD yet, please answer my above questions.

Completely agree. No any convincing reason. The way to go is to enhance the existing functionality rather then duplicating it with minor changes

**Comment by haris-khan1596** [comment]
As suggested by expert reviewers, we will close this HLD pull request. Additionally, we intend to create a new PR for the vrf code improvement (as suggested by @venkatmahalingam) and update the [sonic-vrf-hld.md](https://github.com/sonic-net/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md) accordingly.

**Pull request closed without merging**
