### PR TITLE
SONiC 202311 release notes

### PR DESCRIPTION
**Pull request by kannankvs**
Have come up with the initial version of the SONiC 202311 release notes.

@zhangyanzhao As suggested, we have updated the quality parameter as Alpha for all features. And we need information on one feature ( Upgrade hsflowd and remove dropmon build flags ) to be updated (mentioned as TBD as of now) as there is no information on the same in its PR. 

@skg-net  Request to kindly validate the quality parameter with feature owners for all features present in the release note.

### CODE REVIEW

**Comment by zhangyanzhao** [comment]
I will double check the feature list. So keep this PR open for now.

**Comment by zhangyanzhao** [comment]
@kannankvs I updated the completed feature list on https://github.com/orgs/sonic-net/projects/14/views/1?groupedBy%5BcolumnId%5D=Status, can you please help to double check and merge them into the release notes? Thanks.

**Comment by zhangyanzhao** [comment]
@qiluo-msft  and @yxieca  can you please help to review the security update section to see if it is accurate or anything else is missed? Thanks.

**Review by zhangyanzhao — APPROVED** [review]

**Comment by zhangyanzhao** [comment]
merge the PR with the comments addressed.

**Comment by roy-sror** [comment]
@skg-net, @zhangyanzhao  - can you please help in correcting the quality level of the following features, where tests are available:
1. [DASH] ACL tags HLD, sonic-mgmt: https://github.com/sonic-net/sonic-mgmt/pull/11559
2. FRR version 8.5.1 Upgrade- this is an upgrade of the an existing package that was validated using the existing test, the quality level has to be change to GA
3. Factory reset, sonic-mgmt: https://github.com/sonic-net/sonic-mgmt/pull/7652
4. Persistent DNS address across reboots, sonic-mgmt: https://github.com/sonic-net/sonic-mgmt/pull/8712

**Comment by zhangyanzhao** [comment]
> @skg-net, @zhangyanzhao - can you please help in correcting the quality level of the following features, where tests are available:
> 
> 1. [DASH] ACL tags HLD, sonic-mgmt: [[DASH] New test cases for dash acl tag sonic-mgmt#11559](https://github.com/sonic-net/sonic-mgmt/pull/11559)
> 2. FRR version 8.5.1 Upgrade- this is an upgrade of the an existing package that was validated using the existing test, the quality level has to be change to GA
> 3. Factory reset, sonic-mgmt: [Reset factory tests sonic-mgmt#7652](https://github.com/sonic-net/sonic-mgmt/pull/7652)
> 4. Persistent DNS address across reboots, sonic-mgmt: [Add static DNS test cases sonic-mgmt#8712](https://github.com/sonic-net/sonic-mgmt/pull/8712)
> 5. CMIS related features: were qualified using the existing test suites.

@roy-sror can you please help to update each item and let us know if existing tests have been completed, any regression?

**Comment by zhangyanzhao** [comment]
@roy-sror  kindly ping to address my comments. Thanks.

**Comment by roy-sror** [comment]
@zhangyanzhao - here's the PR that updates the RN:
https://github.com/nhe-NV/SONiC/pull/1

The existing tests were completed, no regressions. I am aware of couple CMIS issues that still have to be resolved.

**Comment by zhangyanzhao** [comment]
> @zhangyanzhao - here's the PR that updates the RN: [nhe-NV#1](https://github.com/nhe-NV/SONiC/pull/1)
> 
> The existing tests were completed, no regressions. I am aware of couple CMIS issues that still have to be resolved.

@roy-sror   the PR you mentioned pointed to a personal repo instead of SONiC community repo, can we ask nhe-NV to raise a PR to SONiC repo? Also from your update, seems like the CMIS has regression, please help to address before we can mark that feature as beta. Thanks.

**Pull request merged**
