### PR TITLE
STP/PVST documentation update

### PR DESCRIPTION
**Pull request by vinaykumar-kayyur**
Added detailed description explained in the document, to the config parameters and SONiC CLI commands for STP/PVST feature. Also refined the existing descriptions for a better readability.

### CODE REVIEW

**Comment by vinaykumar-kayyur** [comment]
@adyeung - Request you to assign appropriate reviewers to review the PVST/STP documentation updates proposed through this PR.

**Comment by adyeung** [comment]
@ridahanif96 @divyachandralekha pls review

**Review by ridahanif96 — APPROVED** [review]
LGTM

**Review by divyachandralekha — APPROVED** [review]

**Comment by vinaykumar-kayyur** [comment]
Thank you @ridahanif96 @divyachandralekha for your kind review and the PR approval.

**Review by ridahanif96 — APPROVED** [review]

**Comment by vinaykumar-kayyur** [comment]
@adyeung @ridahanif96 Thank you for the PR approval and the quick merge into the repository. Truly appreciate your help with this.

**Pull request merged**
